const vsCodeSettings = require('./.vscode/settings.json');

module.exports = {
  $schema:
    'https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json',
  allowCompoundWords: true,
  caseSensitive: true,
  dictionaries: [
    'bash',
    'en_us',
    'en-gb',
    'fonts',
    'html',
    'lorem-ipsum',
    'node',
    'npm',
    'pt-br',
    'typescript',
  ],
  ignorePaths: [
    'dist',
    'node_modules',
    'local',
    'nx.json',
    'package.json',
    'pnpm-lock.yaml',
    'tmp',
    '.vscode',
    '.gitignore',
    'cspell.config.js',
    '*.tfstate*',
    '*.snap',
    '.env-files',
    'apps/infra/terraform-cloud/src/aws-iam',
    'apps/infra/terraform-cloud/src/aws-iam',
    'apps/infra/mongo/src/locals.tf',
    'apps/infra/terraform-cloud/src/.variables/development.tfvars',
    'apps/infra/terraform-cloud/src/.variables/production.tfvars',
    '.terraform.lock.hcl',
  ],
  ignoreWords: vsCodeSettings['cSpell.ignoreWords'],
  import: ['./node_modules/@cspell/dict-pt-br/cspell-ext.json'],
  language: 'en',
  useGitignore: true,
  version: '0.2',
  words: vsCodeSettings['cSpell.words'],
};
